version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      github.com/uptrace/bun:
        applies-to: version-updates
        patterns:
          - "github.com/uptrace/bun"
          - "github.com/uptrace/bun/*"
      go.opentelemetry.io/otel:
        applies-to: version-updates
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/sdk"
          - "go.opentelemetry.io/otel/trace"
      go.opentelemetry.io/otel/log:
        applies-to: version-updates
        patterns:
          - "go.opentelemetry.io/otel/exporters/stdout/stdoutlog"
          - "go.opentelemetry.io/otel/log"
          - "go.opentelemetry.io/otel/sdk/log"
      github.com/getsentry/sentry-go:
        applies-to: version-updates
        patterns:
          - "github.com/getsentry/sentry-go"
          - "github.com/getsentry/sentry-go/*"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
