// Code generated by mockery v2.46.0. DO NOT EDIT.

package loggersmocks

import (
	loggers "github.com/a-novel/golib/loggers"
	mock "github.com/stretchr/testify/mock"
)

// MockConsole is an autogenerated mock type for the Console type
type MockConsole struct {
	mock.Mock
}

type MockConsole_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsole) EXPECT() *MockConsole_Expecter {
	return &MockConsole_Expecter{mock: &_m.Mock}
}

// Log provides a mock function with given fields: level, msg
func (_m *MockConsole) Log(level loggers.LogLevel, msg string) {
	_m.Called(level, msg)
}

// MockConsole_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockConsole_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - level loggers.LogLevel
//   - msg string
func (_e *MockConsole_Expecter) Log(level interface{}, msg interface{}) *MockConsole_Log_Call {
	return &MockConsole_Log_Call{Call: _e.mock.On("Log", level, msg)}
}

func (_c *MockConsole_Log_Call) Run(run func(level loggers.LogLevel, msg string)) *MockConsole_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(loggers.LogLevel), args[1].(string))
	})
	return _c
}

func (_c *MockConsole_Log_Call) Return() *MockConsole_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsole_Log_Call) RunAndReturn(run func(loggers.LogLevel, string)) *MockConsole_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsole creates a new instance of MockConsole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsole(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsole {
	mock := &MockConsole{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
