// Code generated by mockery v2.46.3. DO NOT EDIT.

package loggersmocks

import (
	zerolog "github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// MockZerologMessage is an autogenerated mock type for the ZerologMessage type
type MockZerologMessage struct {
	mock.Mock
}

type MockZerologMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZerologMessage) EXPECT() *MockZerologMessage_Expecter {
	return &MockZerologMessage_Expecter{mock: &_m.Mock}
}

// ZeroLog provides a mock function with given fields: e
func (_m *MockZerologMessage) ZeroLog(e *zerolog.Event) {
	_m.Called(e)
}

// MockZerologMessage_ZeroLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZeroLog'
type MockZerologMessage_ZeroLog_Call struct {
	*mock.Call
}

// ZeroLog is a helper method to define mock.On call
//   - e *zerolog.Event
func (_e *MockZerologMessage_Expecter) ZeroLog(e interface{}) *MockZerologMessage_ZeroLog_Call {
	return &MockZerologMessage_ZeroLog_Call{Call: _e.mock.On("ZeroLog", e)}
}

func (_c *MockZerologMessage_ZeroLog_Call) Run(run func(e *zerolog.Event)) *MockZerologMessage_ZeroLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*zerolog.Event))
	})
	return _c
}

func (_c *MockZerologMessage_ZeroLog_Call) Return() *MockZerologMessage_ZeroLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockZerologMessage_ZeroLog_Call) RunAndReturn(run func(*zerolog.Event)) *MockZerologMessage_ZeroLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZerologMessage creates a new instance of MockZerologMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZerologMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZerologMessage {
	mock := &MockZerologMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
