// Code generated by mockery v2.46.0. DO NOT EDIT.

package loggersmocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockGin is an autogenerated mock type for the Gin type
type MockGin struct {
	mock.Mock
}

type MockGin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGin) EXPECT() *MockGin_Expecter {
	return &MockGin_Expecter{mock: &_m.Mock}
}

// Middleware provides a mock function with given fields:
func (_m *MockGin) Middleware() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Middleware")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockGin_Middleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Middleware'
type MockGin_Middleware_Call struct {
	*mock.Call
}

// Middleware is a helper method to define mock.On call
func (_e *MockGin_Expecter) Middleware() *MockGin_Middleware_Call {
	return &MockGin_Middleware_Call{Call: _e.mock.On("Middleware")}
}

func (_c *MockGin_Middleware_Call) Run(run func()) *MockGin_Middleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGin_Middleware_Call) Return(_a0 gin.HandlerFunc) *MockGin_Middleware_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGin_Middleware_Call) RunAndReturn(run func() gin.HandlerFunc) *MockGin_Middleware_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGin creates a new instance of MockGin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGin {
	mock := &MockGin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
