package deploy

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	_ "embed"
	"fmt"
	"log"
	"net"
	"time"

	"github.com/samber/lo"
	"google.golang.org/api/idtoken"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/credentials/oauth"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"

	"github.com/a-novel/golib/loggers"
	"github.com/a-novel/golib/loggers/formatters"
)

//go:embed grpc-config.json
var grpcConfig string //nolint:unused

// GRPCCallback represents the generic signature of an exposed RPC service, as generated by the protoc compiler for Go.
type GRPCCallback[In any, Out any] func(ctx context.Context, input *In, opts ...grpc.CallOption) (*Out, error)

// OpenGRPCConn opens a new connection to an existing GRPC service.
//
// You must ensure to properly close the connection when you are done, using the CloseGRPCConn method.
//
//	conn := deploy.OpenGRPCConn("localhost:50051")
//	defer deploy.CloseGRPCConn(conn)
//
// This method automatically handles authentication under GCP environments.
func OpenGRPCConn(host string, formatter formatters.Formatter) *grpc.ClientConn {
	var opts []grpc.DialOption

	if IsReleaseEnv() {
		// Under release (GCP) environments, use the default TLS configuration and credentials provided by the
		// Cloud environment.
		systemRoots, err := x509.SystemCertPool()
		if err != nil {
			formatter.Log(formatters.NewError(err, "load system root CA certificates"), loggers.LogLevelFatal)
		}

		tokenSource, err := idtoken.NewTokenSource(context.Background(), "https://"+host)
		if err != nil {
			formatter.Log(formatters.NewError(err, "create token source"), loggers.LogLevelFatal)
		}

		cred := credentials.NewTLS(&tls.Config{RootCAs: systemRoots, MinVersion: tls.VersionTLS12})

		// Configure GRPC requests to be automatically authenticated, so Cloud credentials don't have to be
		// managed manually.
		opts = append(
			opts,
			grpc.WithTransportCredentials(cred),
			grpc.WithAuthority(host+":443"),
			grpc.WithPerRPCCredentials(oauth.TokenSource{TokenSource: tokenSource}),
		)
	} else {
		// Under local development, ignore security.
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	}

	// TODO: uncomment when the app grows. This is temporarily deactivated because it drives GCP costs up.
	// opts = append(opts, grpc.WithDefaultServiceConfig(grpcConfig))

	// Open a connection to the service. This connection will remain alive the whole time the server is up.
	conn, err := grpc.NewClient(host, opts...)
	if err != nil {
		formatter.Log(formatters.NewError(err, "connect to service"), loggers.LogLevelFatal)
	}

	return conn
}

// CloseGRPCConn closes an existing connection to a GRPC service.
//
// Must be called after opening a connection with OpenGRPCConn.
func CloseGRPCConn(conn *grpc.ClientConn, formatter formatters.Formatter) {
	if err := conn.Close(); err != nil {
		formatter.Log(formatters.NewError(err, "close connection"), loggers.LogLevelFatal)
	}
}

// DepCheckCallback is a function that checks the health of a list of dependencies, and return an error for any
// failed dependency.
//
// This map must contain every dependency. Healthy dependencies must be associated to a nil error value.
type DepCheckCallback func() map[string]error

// DepCheckServices lists dependencies for each GRPC service. When healthcheck is triggered, a GRPC service will
// be marked as healthy only if every single one of its dependencies is also healthy.
//
// You should only list RPC services here. The generic health (empty key) is automatically handled by the system.
type DepCheckServices map[string][]string

// DepsCheck configures a health checker for a GRPC service. This healthcheck is run periodically, and will prevent
// faulty calls to unhealthy services.
type DepsCheck struct {
	Dependencies DepCheckCallback
	Services     DepCheckServices
}

// StartGRPCServer starts a new GRPC server on the specified port.
//
// You must ensure to properly close the server when you are done, using the CloseGRPCServer method.
//
//	listener, server, health := deploy.StartGRPCServer(50051)
//	// Graceful shutdown.
//	defer deploy.CloseGRPCServer(listener, server)
//	// (optional, but recommended) Start healthcheck.
//	go health()
func StartGRPCServer(
	port int,
	depsCheck DepsCheck,
	formatter formatters.Formatter,
) (net.Listener, *grpc.Server, func()) {
	// Prevent accidental misconfigurations.
	if port == 0 {
		log.Fatal("port is required")
	}

	// Start to listen on the provided port.
	listener, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		formatter.Log(formatters.NewError(err, "listen"), loggers.LogLevelFatal)
	}

	server := grpc.NewServer()

	// Set healthcheck.
	// https://github.com/grpc/grpc-go/blob/master/examples/features/health/server/main.go
	healthcheck := health.NewServer()
	grpc_health_v1.RegisterHealthServer(server, healthcheck)

	healthUpdater := func() {
		// List the statuses of every dependency. Unhealthy dependencies will report an error.
		dependencies := depsCheck.Dependencies()
		// Health of the global service. If any dependency is unhealthy, the whole service will be marked as unhealthy.
		global := true

		// Check each dependency individually. Add some logs in case of failure, so the issue can be quickly identified.
		// This loop reports errors, and sets the global service health.
		for dependency, err := range dependencies {
			if err != nil {
				formatter.Log(
					formatters.NewError(err, fmt.Sprintf("dependency check for %s failed", dependency)),
					loggers.LogLevelError,
				)
				global = false
			}
		}

		// Check services individually.
		for service, serviceDeps := range depsCheck.Services {
			// Check if any of the current service dependencies is unhealthy.
			_, hasError := lo.Find(serviceDeps, func(item string) bool {
				return dependencies[item] != nil
			})

			healthcheck.SetServingStatus(
				service,
				lo.Ternary(
					hasError,
					grpc_health_v1.HealthCheckResponse_NOT_SERVING,
					grpc_health_v1.HealthCheckResponse_SERVING,
				),
			)
		}

		healthcheck.SetServingStatus(
			"",
			lo.Ternary(
				global,
				grpc_health_v1.HealthCheckResponse_SERVING,
				grpc_health_v1.HealthCheckResponse_NOT_SERVING,
			),
		)

		// Repeat healthcheck every 5 second.
		time.Sleep(5 * time.Second)
	}

	return listener, server, healthUpdater
}

// CloseGRPCServer closes an existing GRPC server.
func CloseGRPCServer(listener net.Listener, server *grpc.Server) {
	server.GracefulStop()
	_ = listener.Close()
}

// CallGRPCEndpoint performs a call to a GRPC endpoint, located in a secure cloud environment.
func CallGRPCEndpoint[In any, Out any](
	ctx context.Context, callback GRPCCallback[In, Out], input *In,
) (*Out, error) {
	// Prevent the call from tasking too long.
	localCTX, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	// Call the GRPC endpoint.
	res, err := callback(localCTX, input)
	if err != nil {
		return nil, err
	}

	return res, nil
}
