// Code generated by mockery v2.46.3. DO NOT EDIT.

package formattersmocks

import mock "github.com/stretchr/testify/mock"

// MockLogContent is an autogenerated mock type for the LogContent type
type MockLogContent struct {
	mock.Mock
}

type MockLogContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogContent) EXPECT() *MockLogContent_Expecter {
	return &MockLogContent_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogContent) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogContent_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogContent_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogContent_Expecter) RenderConsole() *MockLogContent_RenderConsole_Call {
	return &MockLogContent_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogContent_RenderConsole_Call) Run(run func()) *MockLogContent_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogContent_RenderConsole_Call) Return(_a0 string) *MockLogContent_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogContent_RenderConsole_Call) RunAndReturn(run func() string) *MockLogContent_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogContent) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogContent_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogContent_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogContent_Expecter) RenderJSON() *MockLogContent_RenderJSON_Call {
	return &MockLogContent_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogContent_RenderJSON_Call) Run(run func()) *MockLogContent_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogContent_RenderJSON_Call) Return(_a0 interface{}) *MockLogContent_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogContent_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogContent_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogContent creates a new instance of MockLogContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogContent {
	mock := &MockLogContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
