// Code generated by mockery v2.46.3. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	mock "github.com/stretchr/testify/mock"
)

// MockLogTitle is an autogenerated mock type for the LogTitle type
type MockLogTitle struct {
	mock.Mock
}

type MockLogTitle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogTitle) EXPECT() *MockLogTitle_Expecter {
	return &MockLogTitle_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogTitle) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogTitle_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogTitle_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogTitle_Expecter) RenderConsole() *MockLogTitle_RenderConsole_Call {
	return &MockLogTitle_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogTitle_RenderConsole_Call) Run(run func()) *MockLogTitle_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogTitle_RenderConsole_Call) Return(_a0 string) *MockLogTitle_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogTitle_RenderConsole_Call) RunAndReturn(run func() string) *MockLogTitle_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogTitle) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogTitle_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogTitle_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogTitle_Expecter) RenderJSON() *MockLogTitle_RenderJSON_Call {
	return &MockLogTitle_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogTitle_RenderJSON_Call) Run(run func()) *MockLogTitle_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogTitle_RenderJSON_Call) Return(_a0 interface{}) *MockLogTitle_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogTitle_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogTitle_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetChild provides a mock function with given fields: child
func (_m *MockLogTitle) SetChild(child formatters.LogContent) formatters.LogTitle {
	ret := _m.Called(child)

	if len(ret) == 0 {
		panic("no return value specified for SetChild")
	}

	var r0 formatters.LogTitle
	if rf, ok := ret.Get(0).(func(formatters.LogContent) formatters.LogTitle); ok {
		r0 = rf(child)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogTitle)
		}
	}

	return r0
}

// MockLogTitle_SetChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChild'
type MockLogTitle_SetChild_Call struct {
	*mock.Call
}

// SetChild is a helper method to define mock.On call
//   - child formatters.LogContent
func (_e *MockLogTitle_Expecter) SetChild(child interface{}) *MockLogTitle_SetChild_Call {
	return &MockLogTitle_SetChild_Call{Call: _e.mock.On("SetChild", child)}
}

func (_c *MockLogTitle_SetChild_Call) Run(run func(child formatters.LogContent)) *MockLogTitle_SetChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(formatters.LogContent))
	})
	return _c
}

func (_c *MockLogTitle_SetChild_Call) Return(_a0 formatters.LogTitle) *MockLogTitle_SetChild_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogTitle_SetChild_Call) RunAndReturn(run func(formatters.LogContent) formatters.LogTitle) *MockLogTitle_SetChild_Call {
	_c.Call.Return(run)
	return _c
}

// SetDescription provides a mock function with given fields: description
func (_m *MockLogTitle) SetDescription(description string) formatters.LogTitle {
	ret := _m.Called(description)

	if len(ret) == 0 {
		panic("no return value specified for SetDescription")
	}

	var r0 formatters.LogTitle
	if rf, ok := ret.Get(0).(func(string) formatters.LogTitle); ok {
		r0 = rf(description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogTitle)
		}
	}

	return r0
}

// MockLogTitle_SetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDescription'
type MockLogTitle_SetDescription_Call struct {
	*mock.Call
}

// SetDescription is a helper method to define mock.On call
//   - description string
func (_e *MockLogTitle_Expecter) SetDescription(description interface{}) *MockLogTitle_SetDescription_Call {
	return &MockLogTitle_SetDescription_Call{Call: _e.mock.On("SetDescription", description)}
}

func (_c *MockLogTitle_SetDescription_Call) Run(run func(description string)) *MockLogTitle_SetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogTitle_SetDescription_Call) Return(_a0 formatters.LogTitle) *MockLogTitle_SetDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogTitle_SetDescription_Call) RunAndReturn(run func(string) formatters.LogTitle) *MockLogTitle_SetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogTitle creates a new instance of MockLogTitle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogTitle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogTitle {
	mock := &MockLogTitle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
