// Code generated by mockery v2.46.3. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	mock "github.com/stretchr/testify/mock"
)

// MockLogMigrationsList is an autogenerated mock type for the LogMigrationsList type
type MockLogMigrationsList struct {
	mock.Mock
}

type MockLogMigrationsList_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogMigrationsList) EXPECT() *MockLogMigrationsList_Expecter {
	return &MockLogMigrationsList_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogMigrationsList) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogMigrationsList_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogMigrationsList_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogMigrationsList_Expecter) RenderConsole() *MockLogMigrationsList_RenderConsole_Call {
	return &MockLogMigrationsList_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogMigrationsList_RenderConsole_Call) Run(run func()) *MockLogMigrationsList_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogMigrationsList_RenderConsole_Call) Return(_a0 string) *MockLogMigrationsList_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogMigrationsList_RenderConsole_Call) RunAndReturn(run func() string) *MockLogMigrationsList_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogMigrationsList) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogMigrationsList_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogMigrationsList_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogMigrationsList_Expecter) RenderJSON() *MockLogMigrationsList_RenderJSON_Call {
	return &MockLogMigrationsList_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogMigrationsList_RenderJSON_Call) Run(run func()) *MockLogMigrationsList_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogMigrationsList_RenderJSON_Call) Return(_a0 interface{}) *MockLogMigrationsList_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogMigrationsList_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogMigrationsList_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastAppliedGroup provides a mock function with given fields: groupID
func (_m *MockLogMigrationsList) SetLastAppliedGroup(groupID int64) formatters.LogMigrationsList {
	ret := _m.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for SetLastAppliedGroup")
	}

	var r0 formatters.LogMigrationsList
	if rf, ok := ret.Get(0).(func(int64) formatters.LogMigrationsList); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogMigrationsList)
		}
	}

	return r0
}

// MockLogMigrationsList_SetLastAppliedGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastAppliedGroup'
type MockLogMigrationsList_SetLastAppliedGroup_Call struct {
	*mock.Call
}

// SetLastAppliedGroup is a helper method to define mock.On call
//   - groupID int64
func (_e *MockLogMigrationsList_Expecter) SetLastAppliedGroup(groupID interface{}) *MockLogMigrationsList_SetLastAppliedGroup_Call {
	return &MockLogMigrationsList_SetLastAppliedGroup_Call{Call: _e.mock.On("SetLastAppliedGroup", groupID)}
}

func (_c *MockLogMigrationsList_SetLastAppliedGroup_Call) Run(run func(groupID int64)) *MockLogMigrationsList_SetLastAppliedGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockLogMigrationsList_SetLastAppliedGroup_Call) Return(_a0 formatters.LogMigrationsList) *MockLogMigrationsList_SetLastAppliedGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogMigrationsList_SetLastAppliedGroup_Call) RunAndReturn(run func(int64) formatters.LogMigrationsList) *MockLogMigrationsList_SetLastAppliedGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogMigrationsList creates a new instance of MockLogMigrationsList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogMigrationsList(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogMigrationsList {
	mock := &MockLogMigrationsList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
