// Code generated by mockery v2.46.3. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	mock "github.com/stretchr/testify/mock"
)

// MockLogDynamicContent is an autogenerated mock type for the LogDynamicContent type
type MockLogDynamicContent struct {
	mock.Mock
}

type MockLogDynamicContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogDynamicContent) EXPECT() *MockLogDynamicContent_Expecter {
	return &MockLogDynamicContent_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogDynamicContent) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogDynamicContent_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogDynamicContent_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogDynamicContent_Expecter) RenderConsole() *MockLogDynamicContent_RenderConsole_Call {
	return &MockLogDynamicContent_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogDynamicContent_RenderConsole_Call) Run(run func()) *MockLogDynamicContent_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogDynamicContent_RenderConsole_Call) Return(_a0 string) *MockLogDynamicContent_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContent_RenderConsole_Call) RunAndReturn(run func() string) *MockLogDynamicContent_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderConsoleDynamic provides a mock function with given fields: renderer
func (_m *MockLogDynamicContent) RenderConsoleDynamic(renderer func(string)) formatters.LogDynamicContent {
	ret := _m.Called(renderer)

	if len(ret) == 0 {
		panic("no return value specified for RenderConsoleDynamic")
	}

	var r0 formatters.LogDynamicContent
	if rf, ok := ret.Get(0).(func(func(string)) formatters.LogDynamicContent); ok {
		r0 = rf(renderer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogDynamicContent)
		}
	}

	return r0
}

// MockLogDynamicContent_RenderConsoleDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsoleDynamic'
type MockLogDynamicContent_RenderConsoleDynamic_Call struct {
	*mock.Call
}

// RenderConsoleDynamic is a helper method to define mock.On call
//   - renderer func(string)
func (_e *MockLogDynamicContent_Expecter) RenderConsoleDynamic(renderer interface{}) *MockLogDynamicContent_RenderConsoleDynamic_Call {
	return &MockLogDynamicContent_RenderConsoleDynamic_Call{Call: _e.mock.On("RenderConsoleDynamic", renderer)}
}

func (_c *MockLogDynamicContent_RenderConsoleDynamic_Call) Run(run func(renderer func(string))) *MockLogDynamicContent_RenderConsoleDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string)))
	})
	return _c
}

func (_c *MockLogDynamicContent_RenderConsoleDynamic_Call) Return(_a0 formatters.LogDynamicContent) *MockLogDynamicContent_RenderConsoleDynamic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContent_RenderConsoleDynamic_Call) RunAndReturn(run func(func(string)) formatters.LogDynamicContent) *MockLogDynamicContent_RenderConsoleDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogDynamicContent) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogDynamicContent_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogDynamicContent_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogDynamicContent_Expecter) RenderJSON() *MockLogDynamicContent_RenderJSON_Call {
	return &MockLogDynamicContent_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogDynamicContent_RenderJSON_Call) Run(run func()) *MockLogDynamicContent_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogDynamicContent_RenderJSON_Call) Return(_a0 interface{}) *MockLogDynamicContent_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContent_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogDynamicContent_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// StopRunning provides a mock function with given fields:
func (_m *MockLogDynamicContent) StopRunning() formatters.LogDynamicContent {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopRunning")
	}

	var r0 formatters.LogDynamicContent
	if rf, ok := ret.Get(0).(func() formatters.LogDynamicContent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogDynamicContent)
		}
	}

	return r0
}

// MockLogDynamicContent_StopRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopRunning'
type MockLogDynamicContent_StopRunning_Call struct {
	*mock.Call
}

// StopRunning is a helper method to define mock.On call
func (_e *MockLogDynamicContent_Expecter) StopRunning() *MockLogDynamicContent_StopRunning_Call {
	return &MockLogDynamicContent_StopRunning_Call{Call: _e.mock.On("StopRunning")}
}

func (_c *MockLogDynamicContent_StopRunning_Call) Run(run func()) *MockLogDynamicContent_StopRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogDynamicContent_StopRunning_Call) Return(_a0 formatters.LogDynamicContent) *MockLogDynamicContent_StopRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContent_StopRunning_Call) RunAndReturn(run func() formatters.LogDynamicContent) *MockLogDynamicContent_StopRunning_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogDynamicContent creates a new instance of MockLogDynamicContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogDynamicContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogDynamicContent {
	mock := &MockLogDynamicContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
