// Code generated by mockery v2.46.3. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	mock "github.com/stretchr/testify/mock"
)

// MockLogDynamicContentPure is an autogenerated mock type for the LogDynamicContentPure type
type MockLogDynamicContentPure struct {
	mock.Mock
}

type MockLogDynamicContentPure_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogDynamicContentPure) EXPECT() *MockLogDynamicContentPure_Expecter {
	return &MockLogDynamicContentPure_Expecter{mock: &_m.Mock}
}

// RenderConsoleDynamic provides a mock function with given fields: renderer
func (_m *MockLogDynamicContentPure) RenderConsoleDynamic(renderer func(string)) formatters.LogDynamicContent {
	ret := _m.Called(renderer)

	if len(ret) == 0 {
		panic("no return value specified for RenderConsoleDynamic")
	}

	var r0 formatters.LogDynamicContent
	if rf, ok := ret.Get(0).(func(func(string)) formatters.LogDynamicContent); ok {
		r0 = rf(renderer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogDynamicContent)
		}
	}

	return r0
}

// MockLogDynamicContentPure_RenderConsoleDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsoleDynamic'
type MockLogDynamicContentPure_RenderConsoleDynamic_Call struct {
	*mock.Call
}

// RenderConsoleDynamic is a helper method to define mock.On call
//   - renderer func(string)
func (_e *MockLogDynamicContentPure_Expecter) RenderConsoleDynamic(renderer interface{}) *MockLogDynamicContentPure_RenderConsoleDynamic_Call {
	return &MockLogDynamicContentPure_RenderConsoleDynamic_Call{Call: _e.mock.On("RenderConsoleDynamic", renderer)}
}

func (_c *MockLogDynamicContentPure_RenderConsoleDynamic_Call) Run(run func(renderer func(string))) *MockLogDynamicContentPure_RenderConsoleDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string)))
	})
	return _c
}

func (_c *MockLogDynamicContentPure_RenderConsoleDynamic_Call) Return(_a0 formatters.LogDynamicContent) *MockLogDynamicContentPure_RenderConsoleDynamic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContentPure_RenderConsoleDynamic_Call) RunAndReturn(run func(func(string)) formatters.LogDynamicContent) *MockLogDynamicContentPure_RenderConsoleDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// StopRunning provides a mock function with given fields:
func (_m *MockLogDynamicContentPure) StopRunning() formatters.LogDynamicContent {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopRunning")
	}

	var r0 formatters.LogDynamicContent
	if rf, ok := ret.Get(0).(func() formatters.LogDynamicContent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogDynamicContent)
		}
	}

	return r0
}

// MockLogDynamicContentPure_StopRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopRunning'
type MockLogDynamicContentPure_StopRunning_Call struct {
	*mock.Call
}

// StopRunning is a helper method to define mock.On call
func (_e *MockLogDynamicContentPure_Expecter) StopRunning() *MockLogDynamicContentPure_StopRunning_Call {
	return &MockLogDynamicContentPure_StopRunning_Call{Call: _e.mock.On("StopRunning")}
}

func (_c *MockLogDynamicContentPure_StopRunning_Call) Run(run func()) *MockLogDynamicContentPure_StopRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogDynamicContentPure_StopRunning_Call) Return(_a0 formatters.LogDynamicContent) *MockLogDynamicContentPure_StopRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogDynamicContentPure_StopRunning_Call) RunAndReturn(run func() formatters.LogDynamicContent) *MockLogDynamicContentPure_StopRunning_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogDynamicContentPure creates a new instance of MockLogDynamicContentPure. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogDynamicContentPure(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogDynamicContentPure {
	mock := &MockLogDynamicContentPure{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
