// Code generated by mockery v2.46.0. DO NOT EDIT.

package formattersmocks

import mock "github.com/stretchr/testify/mock"

// MockLogError is an autogenerated mock type for the LogError type
type MockLogError struct {
	mock.Mock
}

type MockLogError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogError) EXPECT() *MockLogError_Expecter {
	return &MockLogError_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogError) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogError_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogError_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogError_Expecter) RenderConsole() *MockLogError_RenderConsole_Call {
	return &MockLogError_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogError_RenderConsole_Call) Run(run func()) *MockLogError_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogError_RenderConsole_Call) Return(_a0 string) *MockLogError_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogError_RenderConsole_Call) RunAndReturn(run func() string) *MockLogError_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogError) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogError_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogError_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogError_Expecter) RenderJSON() *MockLogError_RenderJSON_Call {
	return &MockLogError_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogError_RenderJSON_Call) Run(run func()) *MockLogError_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogError_RenderJSON_Call) Return(_a0 interface{}) *MockLogError_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogError_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogError_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogError creates a new instance of MockLogError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogError {
	mock := &MockLogError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
