// Code generated by mockery v2.46.0. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	lipgloss "github.com/charmbracelet/lipgloss"

	mock "github.com/stretchr/testify/mock"
)

// MockLogBase is an autogenerated mock type for the LogBase type
type MockLogBase struct {
	mock.Mock
}

type MockLogBase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogBase) EXPECT() *MockLogBase_Expecter {
	return &MockLogBase_Expecter{mock: &_m.Mock}
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogBase) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogBase_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogBase_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogBase_Expecter) RenderConsole() *MockLogBase_RenderConsole_Call {
	return &MockLogBase_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogBase_RenderConsole_Call) Run(run func()) *MockLogBase_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogBase_RenderConsole_Call) Return(_a0 string) *MockLogBase_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogBase_RenderConsole_Call) RunAndReturn(run func() string) *MockLogBase_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogBase) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogBase_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogBase_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogBase_Expecter) RenderJSON() *MockLogBase_RenderJSON_Call {
	return &MockLogBase_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogBase_RenderJSON_Call) Run(run func()) *MockLogBase_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogBase_RenderJSON_Call) Return(_a0 interface{}) *MockLogBase_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogBase_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogBase_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetChild provides a mock function with given fields: child
func (_m *MockLogBase) SetChild(child formatters.LogContent) formatters.LogBase {
	ret := _m.Called(child)

	if len(ret) == 0 {
		panic("no return value specified for SetChild")
	}

	var r0 formatters.LogBase
	if rf, ok := ret.Get(0).(func(formatters.LogContent) formatters.LogBase); ok {
		r0 = rf(child)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogBase)
		}
	}

	return r0
}

// MockLogBase_SetChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChild'
type MockLogBase_SetChild_Call struct {
	*mock.Call
}

// SetChild is a helper method to define mock.On call
//   - child formatters.LogContent
func (_e *MockLogBase_Expecter) SetChild(child interface{}) *MockLogBase_SetChild_Call {
	return &MockLogBase_SetChild_Call{Call: _e.mock.On("SetChild", child)}
}

func (_c *MockLogBase_SetChild_Call) Run(run func(child formatters.LogContent)) *MockLogBase_SetChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(formatters.LogContent))
	})
	return _c
}

func (_c *MockLogBase_SetChild_Call) Return(_a0 formatters.LogBase) *MockLogBase_SetChild_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogBase_SetChild_Call) RunAndReturn(run func(formatters.LogContent) formatters.LogBase) *MockLogBase_SetChild_Call {
	_c.Call.Return(run)
	return _c
}

// SetStyle provides a mock function with given fields: style
func (_m *MockLogBase) SetStyle(style lipgloss.Style) formatters.LogBase {
	ret := _m.Called(style)

	if len(ret) == 0 {
		panic("no return value specified for SetStyle")
	}

	var r0 formatters.LogBase
	if rf, ok := ret.Get(0).(func(lipgloss.Style) formatters.LogBase); ok {
		r0 = rf(style)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogBase)
		}
	}

	return r0
}

// MockLogBase_SetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStyle'
type MockLogBase_SetStyle_Call struct {
	*mock.Call
}

// SetStyle is a helper method to define mock.On call
//   - style lipgloss.Style
func (_e *MockLogBase_Expecter) SetStyle(style interface{}) *MockLogBase_SetStyle_Call {
	return &MockLogBase_SetStyle_Call{Call: _e.mock.On("SetStyle", style)}
}

func (_c *MockLogBase_SetStyle_Call) Run(run func(style lipgloss.Style)) *MockLogBase_SetStyle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(lipgloss.Style))
	})
	return _c
}

func (_c *MockLogBase_SetStyle_Call) Return(_a0 formatters.LogBase) *MockLogBase_SetStyle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogBase_SetStyle_Call) RunAndReturn(run func(lipgloss.Style) formatters.LogBase) *MockLogBase_SetStyle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogBase creates a new instance of MockLogBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogBase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogBase {
	mock := &MockLogBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
