// Code generated by mockery v2.46.0. DO NOT EDIT.

package formattersmocks

import (
	formatters "github.com/a-novel/golib/loggers/formatters"
	lipgloss "github.com/charmbracelet/lipgloss"

	list "github.com/charmbracelet/lipgloss/list"

	mock "github.com/stretchr/testify/mock"
)

// MockLogList is an autogenerated mock type for the LogList type
type MockLogList struct {
	mock.Mock
}

type MockLogList_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogList) EXPECT() *MockLogList_Expecter {
	return &MockLogList_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: content
func (_m *MockLogList) Append(content string) formatters.LogList {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(string) formatters.LogList); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockLogList_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - content string
func (_e *MockLogList_Expecter) Append(content interface{}) *MockLogList_Append_Call {
	return &MockLogList_Append_Call{Call: _e.mock.On("Append", content)}
}

func (_c *MockLogList_Append_Call) Run(run func(content string)) *MockLogList_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogList_Append_Call) Return(_a0 formatters.LogList) *MockLogList_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_Append_Call) RunAndReturn(run func(string) formatters.LogList) *MockLogList_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Nest provides a mock function with given fields: content
func (_m *MockLogList) Nest(content formatters.LogContent) formatters.LogList {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Nest")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(formatters.LogContent) formatters.LogList); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_Nest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nest'
type MockLogList_Nest_Call struct {
	*mock.Call
}

// Nest is a helper method to define mock.On call
//   - content formatters.LogContent
func (_e *MockLogList_Expecter) Nest(content interface{}) *MockLogList_Nest_Call {
	return &MockLogList_Nest_Call{Call: _e.mock.On("Nest", content)}
}

func (_c *MockLogList_Nest_Call) Run(run func(content formatters.LogContent)) *MockLogList_Nest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(formatters.LogContent))
	})
	return _c
}

func (_c *MockLogList_Nest_Call) Return(_a0 formatters.LogList) *MockLogList_Nest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_Nest_Call) RunAndReturn(run func(formatters.LogContent) formatters.LogList) *MockLogList_Nest_Call {
	_c.Call.Return(run)
	return _c
}

// RenderConsole provides a mock function with given fields:
func (_m *MockLogList) RenderConsole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderConsole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLogList_RenderConsole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderConsole'
type MockLogList_RenderConsole_Call struct {
	*mock.Call
}

// RenderConsole is a helper method to define mock.On call
func (_e *MockLogList_Expecter) RenderConsole() *MockLogList_RenderConsole_Call {
	return &MockLogList_RenderConsole_Call{Call: _e.mock.On("RenderConsole")}
}

func (_c *MockLogList_RenderConsole_Call) Run(run func()) *MockLogList_RenderConsole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogList_RenderConsole_Call) Return(_a0 string) *MockLogList_RenderConsole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_RenderConsole_Call) RunAndReturn(run func() string) *MockLogList_RenderConsole_Call {
	_c.Call.Return(run)
	return _c
}

// RenderJSON provides a mock function with given fields:
func (_m *MockLogList) RenderJSON() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenderJSON")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockLogList_RenderJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderJSON'
type MockLogList_RenderJSON_Call struct {
	*mock.Call
}

// RenderJSON is a helper method to define mock.On call
func (_e *MockLogList_Expecter) RenderJSON() *MockLogList_RenderJSON_Call {
	return &MockLogList_RenderJSON_Call{Call: _e.mock.On("RenderJSON")}
}

func (_c *MockLogList_RenderJSON_Call) Run(run func()) *MockLogList_RenderJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogList_RenderJSON_Call) Return(_a0 interface{}) *MockLogList_RenderJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_RenderJSON_Call) RunAndReturn(run func() interface{}) *MockLogList_RenderJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnumerator provides a mock function with given fields: enumerator
func (_m *MockLogList) SetEnumerator(enumerator list.Enumerator) formatters.LogList {
	ret := _m.Called(enumerator)

	if len(ret) == 0 {
		panic("no return value specified for SetEnumerator")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(list.Enumerator) formatters.LogList); ok {
		r0 = rf(enumerator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_SetEnumerator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnumerator'
type MockLogList_SetEnumerator_Call struct {
	*mock.Call
}

// SetEnumerator is a helper method to define mock.On call
//   - enumerator list.Enumerator
func (_e *MockLogList_Expecter) SetEnumerator(enumerator interface{}) *MockLogList_SetEnumerator_Call {
	return &MockLogList_SetEnumerator_Call{Call: _e.mock.On("SetEnumerator", enumerator)}
}

func (_c *MockLogList_SetEnumerator_Call) Run(run func(enumerator list.Enumerator)) *MockLogList_SetEnumerator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(list.Enumerator))
	})
	return _c
}

func (_c *MockLogList_SetEnumerator_Call) Return(_a0 formatters.LogList) *MockLogList_SetEnumerator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_SetEnumerator_Call) RunAndReturn(run func(list.Enumerator) formatters.LogList) *MockLogList_SetEnumerator_Call {
	_c.Call.Return(run)
	return _c
}

// SetIndenter provides a mock function with given fields: indenter
func (_m *MockLogList) SetIndenter(indenter list.Indenter) formatters.LogList {
	ret := _m.Called(indenter)

	if len(ret) == 0 {
		panic("no return value specified for SetIndenter")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(list.Indenter) formatters.LogList); ok {
		r0 = rf(indenter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_SetIndenter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIndenter'
type MockLogList_SetIndenter_Call struct {
	*mock.Call
}

// SetIndenter is a helper method to define mock.On call
//   - indenter list.Indenter
func (_e *MockLogList_Expecter) SetIndenter(indenter interface{}) *MockLogList_SetIndenter_Call {
	return &MockLogList_SetIndenter_Call{Call: _e.mock.On("SetIndenter", indenter)}
}

func (_c *MockLogList_SetIndenter_Call) Run(run func(indenter list.Indenter)) *MockLogList_SetIndenter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(list.Indenter))
	})
	return _c
}

func (_c *MockLogList_SetIndenter_Call) Return(_a0 formatters.LogList) *MockLogList_SetIndenter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_SetIndenter_Call) RunAndReturn(run func(list.Indenter) formatters.LogList) *MockLogList_SetIndenter_Call {
	_c.Call.Return(run)
	return _c
}

// SetItemStyle provides a mock function with given fields: style
func (_m *MockLogList) SetItemStyle(style lipgloss.Style) formatters.LogList {
	ret := _m.Called(style)

	if len(ret) == 0 {
		panic("no return value specified for SetItemStyle")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(lipgloss.Style) formatters.LogList); ok {
		r0 = rf(style)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_SetItemStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetItemStyle'
type MockLogList_SetItemStyle_Call struct {
	*mock.Call
}

// SetItemStyle is a helper method to define mock.On call
//   - style lipgloss.Style
func (_e *MockLogList_Expecter) SetItemStyle(style interface{}) *MockLogList_SetItemStyle_Call {
	return &MockLogList_SetItemStyle_Call{Call: _e.mock.On("SetItemStyle", style)}
}

func (_c *MockLogList_SetItemStyle_Call) Run(run func(style lipgloss.Style)) *MockLogList_SetItemStyle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(lipgloss.Style))
	})
	return _c
}

func (_c *MockLogList_SetItemStyle_Call) Return(_a0 formatters.LogList) *MockLogList_SetItemStyle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_SetItemStyle_Call) RunAndReturn(run func(lipgloss.Style) formatters.LogList) *MockLogList_SetItemStyle_Call {
	_c.Call.Return(run)
	return _c
}

// SetStyle provides a mock function with given fields: style
func (_m *MockLogList) SetStyle(style lipgloss.Style) formatters.LogList {
	ret := _m.Called(style)

	if len(ret) == 0 {
		panic("no return value specified for SetStyle")
	}

	var r0 formatters.LogList
	if rf, ok := ret.Get(0).(func(lipgloss.Style) formatters.LogList); ok {
		r0 = rf(style)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(formatters.LogList)
		}
	}

	return r0
}

// MockLogList_SetStyle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStyle'
type MockLogList_SetStyle_Call struct {
	*mock.Call
}

// SetStyle is a helper method to define mock.On call
//   - style lipgloss.Style
func (_e *MockLogList_Expecter) SetStyle(style interface{}) *MockLogList_SetStyle_Call {
	return &MockLogList_SetStyle_Call{Call: _e.mock.On("SetStyle", style)}
}

func (_c *MockLogList_SetStyle_Call) Run(run func(style lipgloss.Style)) *MockLogList_SetStyle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(lipgloss.Style))
	})
	return _c
}

func (_c *MockLogList_SetStyle_Call) Return(_a0 formatters.LogList) *MockLogList_SetStyle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogList_SetStyle_Call) RunAndReturn(run func(lipgloss.Style) formatters.LogList) *MockLogList_SetStyle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogList creates a new instance of MockLogList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogList(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogList {
	mock := &MockLogList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
