name: auto-approve dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.event.pull_request.user.login }}
      - uses: a-novel-kit/workflows/generic-actions/approve-bot@master
        if: github.event.pull_request.user.login == 'renovate[bot]'
        with:
          pull_request: ${{ github.event.pull_request.html_url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
